# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: |
  Behavior for temporarily changing keybind processor configuration.
  When pressed, applies temporary configuration. When released, restores original settings.

compatible: "zmk,behavior-input-processor-keybind-temp-config"

include: ../zmk,behavior-key-toggle.yaml

properties:
  processor-name:
    type: string
    required: true
    description: Name of the keybind processor to configure

  tick:
    type: int
    description: Temporary tick value (movement units per activation)

  degree-offset:
    type: int
    description: Temporary degree offset (0-359)

  wait-ms:
    type: int
    description: Temporary wait delay (milliseconds)

  tap-ms:
    type: int
    description: Temporary tap duration (milliseconds)
